# Generated by Django 3.0 on 2019-12-10 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fadollproducts', '0002_auto_20191210_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='ProductImage',
            field=models.TextField(max_length=255),
        ),
    ]
