# Generated by Django 3.0 on 2019-12-10 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fadollproducts', '0003_auto_20191210_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattributes',
            name='ProductAttributes',
            field=models.TextField(default=True, max_length=100),
        ),
    ]
