# Generated by Django 3.0 on 2019-12-10 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fadollproducts', '0004_productattributes_productattributes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productattributes',
            old_name='ProductAttributes',
            new_name='ProductAttributesName',
        ),
    ]
