# Generated by Django 3.0 on 2020-03-19 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fadollproducts', '0005_auto_20191210_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productattributes',
            name='ProductAttributesName',
        ),
        migrations.AlterField(
            model_name='attributes',
            name='AttributeName',
            field=models.CharField(max_length=80, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='CreatedDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='ModifiedDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
