# Generated by Django 3.0 on 2020-03-19 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fadollproducts', '0006_auto_20200319_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='CreatedDate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='ModifiedDate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
