# Generated by Django 3.0 on 2020-03-23 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fadollproducts', '0008_auto_20200319_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='CreatedDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='ModifiedDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
